@startuml
mainframe part 1
'skinparam packageStyle rectangle
skinparam linetype ortho

top to bottom direction

title Configurations are used to initialize the harness

package "Configurations" {
    ' Configuration class to the left of Facades

    class Configuration {
    }
    class Initializer {
    }
    note top
Configurations depend on everything else
and are used to
- read the configuration data from files or env var
- validate it
- do a sanity check on existing devices
- initialize the harness
end note

    class Validator {}
    class ConfigurationFileReader {}

}


' Facades at the top
package "Facades" {


}

'Configuration -[hidden]right- Facades

' Wrappers and Devices in the middle
package "Wrappers" {

}



package "Actions" {

}
' ensure Actions are below Wrappers
'"Wrappers" -[hidden]down--- Actions
Actions .left.> Wrappers
"Facades" ..left..> Actions
"Configurations" ..> Actions
"Configurations" ..> Facades
"Configurations" ..> Wrappers

' Stacking packages vertically
'Facades -[hidden]down- "Wrappers"
Facades ..right..> "Wrappers"


@enduml