@startuml
mainframe part 2
'skinparam packageStyle rectangle
skinparam linetype ortho

title Facades are used by test scripts

' Enforce vertical layout
top to bottom direction

package "Configurations" {
}


' Facades at the top
package "Facades" {
    class TMCSubarrayNodeFacade {
        + subarray_node: DeviceProxy {property}
        + dish_leaf_node_dict: Dict[str, DeviceProxy] {property}
        + csp_subarray_leaf_node: DeviceProxy {property}
        + sdp_subarray_leaf_node: DeviceProxy {property}
        + set_subarray_id(id)
        + configure(input_string)
        + end_observation()
    }

    note top
    Facades are used by test script to access the components of the SUT
    and to issue commands.
    Each facade is a particular 'view' on the telescope.
    They depend on Wrappers and Actions
    end note

    class CSPFacade {
        + csp_master: DeviceProxy {property}
        + csp_subarray: DeviceProxy {property}
        + method_1()
    }

    class SDPFacade {
        + sdp_master: DeviceProxy {property}
        + sdp_subarray: DeviceProxy {property}
        + method_1()
    }

    class DishesFacade {
        + dish_master_dict: Dict[str, DeviceProxy] {property}
        + method_1()
    }

    class TMCCentralNodeFacade {
        + central_node: DeviceProxy {property}
        + method_1()
    }
}

'Configuration -[hidden]right- Facades

' Wrappers and Devices in the middle
package "Wrappers" {
}



package "Actions" {

}
' ensure Actions are below Wrappers
Actions ..right..> Wrappers
"Facades" ..> Actions
Configurations ..> Facades

' Stacking packages vertically
Facades -[hidden]down- "Wrappers"
Facades ..down..> "Wrappers"


@enduml