@startuml
mainframe part 1
'skinparam packageStyle rectangle
skinparam linetype ortho

top to bottom direction

title Configurations are used to initialize the harness

package "init" {

    class TestHarnessBuilder {
    }

    class TestHarnessFactory {
    }
}

package "config" {

    class TestHarnessConfiguration {
    }

    class YamlConfigurationReader {}

    class ConfigurationValidator {}
}


package "facades" {
}


package "structure" {

}

package "actions" {

}

actions ..> structure
facades ..> actions
facades ..> structure

structure ..> config
init ..> config
init ..> structure

@enduml